### PR TITLE
fix: ci fail

### PR DESCRIPTION
**Pull request by jeromehan**
@h-a-n-a

### CODE REVIEW

**Review by h-a-n-a — APPROVED** [review]
Thank you for the contribution!

**Comment by jeromehan** [comment]
If there are no problems, can we merge into the master branch of vue-loader v15 @h-a-n-a

**Comment by h-a-n-a** [comment]
> If there are no problems, can we merge into the master branch of vue-loader v15 @h-a-n-a 

I don't think they are actively maintain v15 and receive additional PR for this one, so I created this repo only for rspack vue2 users.

**Comment by jeromehan** [comment]
ok

**Pull request merged**
